In [15]:
import numpy as np    # python module useful in handling arrays, vectors, matrices etc.
from numpy import linalg as LA   # for eigenvalue and eigenvector computation

Lets find eigen values and eigen vectors for this matrix

\begin{bmatrix}
   4 & -1 & 5 \\
   0 &  6 & 0 \\
   1 & -2 & 0  
\end{bmatrix}


In [16]:
A = np.matrix('4 -1 5; 0 6 0; 1 -2 0')    # declaring a numpy matrix
print(A)

[[ 4 -1  5]
 [ 0  6  0]
 [ 1 -2  0]]


In [17]:
EigenValues, EigenVectors = LA.eig(A)

In [18]:
EigenValues

array([ 5., -1.,  6.])

In [19]:
EigenVectors

matrix([[ 0.98058068, -0.70710678, -0.88077101],
        [ 0.        ,  0.        ,  0.38533732],
        [ 0.19611614,  0.70710678, -0.27524094]])

In [20]:
print ( "eingenvector for eigenvector", EigenValues[0], "is" , EigenVectors[0] )
print ( "eingenvector for eigenvector", EigenValues[1], "is" , EigenVectors[1] )
print ( "eingenvector for eigenvector", EigenValues[2], "is" , EigenVectors[2] )

eingenvector for eigenvector 5.0 is [[ 0.98058068 -0.70710678 -0.88077101]]
eingenvector for eigenvector -1.0 is [[ 0.          0.          0.38533732]]
eingenvector for eigenvector 6.0 is [[ 0.19611614  0.70710678 -0.27524094]]
